"""进货订单表增加创建时间、完成时间和是否完成字段，历史售出订单增加时间字段

Revision ID: 070fb6b3cf87
Revises: 3e44f97008b4
Create Date: 2021-01-04 21:04:39.607670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '070fb6b3cf87'
down_revision = '3e44f97008b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_orders', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.add_column('sms_purchase', sa.Column('buildtime', sa.DateTime(), nullable=False))
    op.add_column('sms_purchase', sa.Column('finishtime', sa.DateTime(), nullable=True))
    op.add_column('sms_purchase', sa.Column('if_finish', sa.Boolean(), nullable=False))
    op.drop_column('sms_purchase', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_purchase', sa.Column('datetime', mysql.DATETIME(), nullable=False))
    op.drop_column('sms_purchase', 'if_finish')
    op.drop_column('sms_purchase', 'finishtime')
    op.drop_column('sms_purchase', 'buildtime')
    op.drop_column('sms_orders', 'datetime')
    # ### end Alembic commands ###
