"""初步建好数据库

Revision ID: 3e44f97008b4
Revises: f7b3f5ffad53
Create Date: 2021-01-03 18:44:23.999132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e44f97008b4'
down_revision = 'f7b3f5ffad53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_cats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('sign_start', sa.Date(), nullable=False),
    sa.Column('sign_end', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intro', sa.String(length=256), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['sms_cats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['sms_goods.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sms_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id', 'good_id', 'supplier_id')
    )
    op.create_table('sms_purchase',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price_in', sa.Float(), nullable=False),
    sa.Column('if_shelf', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['sms_goods.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sms_suppliers.id'], ),
    sa.PrimaryKeyConstraint('good_id', 'supplier_id', 'datetime')
    )
    op.create_table('sms_sales',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('price_out', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['sms_goods.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sms_suppliers.id'], ),
    sa.PrimaryKeyConstraint('good_id', 'supplier_id')
    )
    op.create_table('sms_stocks',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['sms_goods.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sms_suppliers.id'], ),
    sa.PrimaryKeyConstraint('good_id', 'supplier_id')
    )
    op.alter_column('sms_users', 'name',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_users', 'name',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
    op.drop_table('sms_stocks')
    op.drop_table('sms_sales')
    op.drop_table('sms_purchase')
    op.drop_table('sms_orders')
    op.drop_table('sms_goods')
    op.drop_table('sms_suppliers')
    op.drop_table('sms_cats')
    # ### end Alembic commands ###
