"""供应商地址必填

Revision ID: 65df458fa3f1
Revises: 670984edbf53
Create Date: 2021-01-05 21:14:51.416748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65df458fa3f1'
down_revision = '670984edbf53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_suppliers', 'city',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('sms_suppliers', 'province',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_suppliers', 'province',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('sms_suppliers', 'city',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
