"""更改供应商位置字段

Revision ID: 670984edbf53
Revises: 4906283f0f89
Create Date: 2021-01-05 21:02:24.933342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '670984edbf53'
down_revision = '4906283f0f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_suppliers', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('sms_suppliers', sa.Column('province', sa.String(length=64), nullable=True))
    op.drop_column('sms_suppliers', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_suppliers', sa.Column('address', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('sms_suppliers', 'province')
    op.drop_column('sms_suppliers', 'city')
    # ### end Alembic commands ###
