"""新版数据库

Revision ID: c6b6f577deda
Revises: 
Create Date: 2021-01-10 14:17:51.914394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b6f577deda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_cats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sms_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=64), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('sign_start', sa.Date(), nullable=False),
    sa.Column('sign_end', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intro', sa.String(length=256), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['sms_cats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('mobile', sa.String(length=64), nullable=True),
    sa.Column('area', sa.String(length=256), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sms_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['sms_goods.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sms_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id', 'good_id', 'supplier_id')
    )
    op.create_table('sms_purchase',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('buildtime', sa.DateTime(), nullable=False),
    sa.Column('finishtime', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price_in', sa.Float(), nullable=False),
    sa.Column('if_finish', sa.Boolean(), nullable=False),
    sa.Column('if_shelf', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['sms_goods.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sms_suppliers.id'], ),
    sa.PrimaryKeyConstraint('good_id', 'supplier_id', 'buildtime')
    )
    op.create_table('sms_sales',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('price_out', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['sms_goods.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sms_suppliers.id'], ),
    sa.PrimaryKeyConstraint('good_id', 'supplier_id')
    )
    op.create_table('sms_stocks',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['sms_goods.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sms_suppliers.id'], ),
    sa.PrimaryKeyConstraint('good_id', 'supplier_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms_stocks')
    op.drop_table('sms_sales')
    op.drop_table('sms_purchase')
    op.drop_table('sms_orders')
    op.drop_table('sms_users')
    op.drop_table('sms_goods')
    op.drop_table('sms_suppliers')
    op.drop_table('sms_roles')
    op.drop_table('sms_cats')
    # ### end Alembic commands ###
